### ISSUE TITLE
Compile error when starting up app

### ISSUE THREAD

**Issue by naragon** [ng2-ui/ng2-react#2]
I pullled down the latest code and ran the following instructions:
```
$ git clone https://github.com/ng2-ui/ng2-react.git
$ cd ng2-react
$ npm install
$ npm start
```
I get the following error in the browser:

```
./src/ng2-react.app.component.ts
(5,41): error TS2407: The right-hand side of a 'for...in' statement must be of type 'any', an object type or a type parameter.
```
Using:  

OSX 10.10.5
node v.6.10.0
npm 3.10.10

**Comment by allenhwkim** [comment]
@naragon thanks for reporting this.
However, I cannot reproduce this issue.

Mac osx 10.11
ng2-react$ (master) node --version
v6.9.0
ng2-react$ (master) npm --version
3.10.9

![image](https://cloud.githubusercontent.com/assets/1437734/24310682/487a19d8-10a7-11e7-8af9-129c43104e53.png)

![image](https://cloud.githubusercontent.com/assets/1437734/24310805/b5c436f4-10a7-11e7-9314-4668f50b7d81.png)

**Comment by naragon** [comment]
Thanks for the quick response Allen. I ran this on a different machine (Ubuntu 16.04)
```
> ng2-react@0.2.1 start /home/naragon/projects/ng2-react
> NODE_ENV=dev webpack-dev-server --quiet --port 9001 --content-base app --config app/webpack.config --open

 http://localhost:9001/webpack-dev-server/
webpack result is served from /build/
content is served from /home/naragon/projects/ng2-react/app
ts-loader: Using typescript@2.2.1 and /home/naragon/projects/ng2-react/tsconfig.json
```
I get the same error. I'm also running the same versions of Node and NPM  and Typescript (2.2.1) as on the Mac. I'll keep looking into it.

**Comment by allenhwkim** [comment]
It might be related angular/angular-cli or webpack version, could you check
those version?

**Comment by naragon** [comment]
Webpack: 2.3.2
```
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.0.0
node: 6.10.0
os: darwin x64
@angular/cli: 1.0.0
@angular/common: 2.4.10
@angular/compiler: 2.4.10
@angular/compiler-cli: 2.4.10
@angular/core: 2.4.10
@angular/forms: 2.4.10
@angular/http: 2.4.10
@angular/platform-browser: 2.4.10
@angular/platform-browser-dynamic: 2.4.10
@angular/router: 3.4.10
```

**Comment by allenhwkim** [comment]
??? it works?

**Comment by allenhwkim** [comment]
Can anyone reproduce this issue? I tried several times, but failed to reproduce.

**Comment by naragon** [comment]
It works now. I pulled down the latest changes. Removed node_modules dir and re-ran install and start. 
<img width="1664" alt="screen shot 2017-03-26 at 5 23 21 pm" src="https://cloud.githubusercontent.com/assets/552404/24335755/1461ad48-1249-11e7-96b7-f308b81d163e.png">

Still not sure what the issue was. Thanks for your assistance Allen.

**Comment by allenhwkim** [comment]
@naragon you're welcome. Please keep watching this repo, and if possible, please consider to become a contributor.
